# Generated by Django 3.1.7 on 2021-03-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieform', '0002_auto_20210322_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMovieModel',
        ),
    ]
