# Generated by Django 3.1.7 on 2021-03-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieform', '0003_delete_addmoviemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('m_kind', models.CharField(max_length=20, verbose_name='Movie Kind')),
                ('m_year', models.CharField(max_length=10, verbose_name='Movie Year')),
                ('m_actors', models.CharField(max_length=100, verbose_name='Movie Actors')),
                ('m_rank', models.CharField(max_length=3, verbose_name='Movie Rank Point')),
                ('m_content', models.TextField(max_length=1000, verbose_name='Movie Content')),
                ('m_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Movie Image')),
            ],
        ),
    ]
